### ISSUE TITLE
Could you please share the email address?

### ISSUE THREAD

**Issue by AK250** [akmtn/OmniDreamer#1]
Hi, 
Thanks for your excellent work! 
I want to send email to get the URL for trained models downloading, but I didn't find the address of email,  could you please share it?

**Comment by MahdiMohseni0033** [comment]
Hello,
I am impressed by your excellent work. I am currently facing a similar issue and I couldn't find your email address anywhere, not on your GitHub repository, not in your paper, or on Google Scholar by searching for your name. Can you please share your email address with me?

**Comment by yosun** [comment]
Same. Why not just share a gDrive link to the trained model

**Comment by akmtn** [comment]
I have published my resume on the web with my email address, which can also be accessed via a link in my github account.
Thanks.
